In [ ]:
from google.colab import drive
import os
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/Colab Notebooks/')
!pwd

In [ ]:
import numpy as np
from numpy import genfromtxt
my_data = genfromtxt('newData.csv', delimiter=',')
X = my_data[:,:5]
Y = my_data[:,6]

In [ ]:
clabels = np.unique(Y, return_counts=True)
nLables = []
nLable = 0
for i,j in np.transpose(clabels):
    print('lable = ',i,'     count = ',j,'       newlable = ',nLable)
    nLables.append((i,nLable))
    nLable = nLable + 1

lable =  1.0      count =  231976.0        newlable =  0
lable =  3.0      count =  20721.0        newlable =  1
lable =  5.0      count =  5789.0        newlable =  2
lable =  8.0      count =  226.0        newlable =  3
lable =  16.0      count =  261298.0        newlable =  4
lable =  26.0      count =  39623.0        newlable =  5
lable =  36.0      count =  1400.0        newlable =  6
lable =  38.0      count =  102.0        newlable =  7


In [ ]:
# painting labels
for i in range(np.shape(Y)[0]):
    for j,k in nLables:
        if Y[i] == j:
            Y[i] = k
            break
Y = np.int32(Y)

In [ ]:
# creating one-hot vectors from labels to be used in NN
import sklearn.preprocessing
label_binarizer = sklearn.preprocessing.LabelBinarizer()
label_binarizer.fit(range(max(Y)+1))
Y = label_binarizer.transform(Y)

print('{0}'.format(Y))

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42, shuffle=True)
X_train , X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size=0.3, random_state=43, shuffle=True)
print('Test Data = ', X_test.shape[0])
print('Validation Data = ', X_val.shape[0])
print('Train Data = ', X_train.shape[0])

Test Data =  112227
Validation Data =  134673
Train Data =  314235


In [ ]:
from __future__ import print_function
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

model = Sequential()
model.add(Dense(5, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='softmax'))
model.compile(loss=keras.losses.binary_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

model.fit(X_train, Y_train,
          batch_size=1024,
          epochs=30,
          verbose=2,
          validation_data=(X_val,Y_val))

Using TensorFlow backend.







Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 314235 samples, validate on 134673 samples
Epoch 1/30





 - 11s - loss: 0.2273 - acc: 0.8859 - val_loss: 0.1912 - val_acc: 0.9113
Epoch 2/30
 - 2s - loss: 0.1837 - acc: 0.9157 - val_loss: 0.1806 - val_acc: 0.9183
Epoch 3/30
 - 2s - loss: 0.1784 - acc: 0.9192 - val_loss: 0.1756 - val_acc: 0.9211
Epoch 4/30
 - 2s - loss: 0.1721 - acc: 0.9226 - val_loss: 0.1688 - val_acc: 0.9240
Epoch 5/30
 - 2s - loss: 0.1674 - acc: 0.9247 - val_loss: 0.1656 - val_acc: 0.9256
Epoch 6/30
 - 1s - loss: 0.1648 - acc: 0.9261 - val_loss: 0.1637 - val_acc: 0.9266
Epoch 7/30
 - 2s - loss: 0.1628 - acc: 0.9267 - val_loss: 0.1619 - val_acc: 0.9269
Epoch 8/30
 - 2s - loss: 0.1611 - acc: 0.9270 - val_loss: 0.1605 - val_acc: 0.9272
Epoch 9/30
 - 2s - loss: 0.1600 - acc: 0.9273 - val_loss: 0.1596 - val_acc: 0.9275
Epoch 10/30
 - 2s - loss: 0.1587 - acc: 0.9277 - val_loss: 0.1581 - val_acc: 0.9282
Epoch 11/

In [ ]:
from sklearn.metrics import classification_report
score = model.evaluate(X_test, Y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(score)

Test loss: 0.14965767703097113
Test accuracy: 0.9320851934031882
[0.14965767703097113, 0.9320851934031882]


In [ ]:
index = 5
x1 = np.reshape(X_test[index],(1,5))
x1

array([[-0.110962,  0.375916,  0.910034, -1.603053, -6.473282]])

In [ ]:
model.predict(x1)

array([[1.01590045e-01, 7.71027757e-04, 1.21037126e-01, 3.44654745e-06,
        7.71190286e-01, 3.07054893e-06, 5.29355137e-03, 1.11441172e-04]],
      dtype=float32)

In [ ]:
Y_train[index]

array([1, 0, 0, 0, 0, 0, 0, 0])